FROM docker.io/python:3-slim-buster
MAINTAINER Niv Sardi <x@filtra.me>
WORKDIR /app

RUN apt update && apt install -y libcairo2 libglib2.0-0 libgl1 && rm -rf /var/cache/apt
COPY python/requirements.txt ./python/requirements.txt
RUN pip install -r ./python/requirements.txt

COPY run.sh ./run
RUN chmod +x run
COPY python ./python

CMD sh -c 'while true; do  echo "🐍 python waiting" ; sleep 2h; done'

