DATA_PATH='./data'

LABELS_PATH=f'{DATA_PATH}/labels'
IMAGES_PATH=f'{DATA_PATH}/images'
CERTS_PATH=f'{DATA_PATH}/certs'

SQUARES_DATA_PATH=f'{DATA_PATH}/squares'
SQUARES_LABELS_PATH=f'{SQUARES_DATA_PATH}/labels'
SQUARES_IMAGES_PATH=f'{SQUARES_DATA_PATH}/images'

DEBUG_PATH=f'{DATA_PATH}/debug'
DEBUG_SQUARES_PATH=f'{DEBUG_PATH}/squares'

LOGOS_DATA_PATH=f'{DATA_PATH}/logos'

MAIN_CSV_PATH=f'{DATA_PATH}/entities.csv'
