#!/usr/bin/env python
import os

def D(n, d):
    return os.environ.get(f'SPOOF_{n}') or d

DATA_PATH = D('DATA_PATH', './data')

LABELS_PATH = D('LABELS_PATH', f'{DATA_PATH}/labels')
IMAGES_PATH = D('IMAGES_PATH', f'{DATA_PATH}/images')
CERTS_PATH = D('CERTS_PATH', f'{DATA_PATH}/certs')
FISH_PATH = D('FISH_PATH', f'{DATA_PATH}/fish')
SCREENSHOT_PATH = D('SCREENSHOT_PATH', f'{DATA_PATH}/screenshots')

SQUARES_DATA_PATH = D('SQUARES_DATA_PATH', f'{DATA_PATH}/squares')
SQUARES_LABELS_PATH = D('SQUARES_LABELS_PATH', f'{SQUARES_DATA_PATH}/labels')
SQUARES_IMAGES_PATH = D('SQUARES_IMAGES_PATH', f'{SQUARES_DATA_PATH}/images')

DEBUG_PATH = D('DEBUG_PATH', f'{DATA_PATH}/debug')
DEBUG_SQUARES_PATH = D('DEBUG_SQUARES_PATH', f'{DEBUG_PATH}/squares')
LOG_PATH = D('LOG_PATH', f'{DATA_PATH}/logs')

LOGOS_DATA_PATH = D('LOGOS_DATA_PATH', f'{DATA_PATH}/logos')

AUGMENTED_DATA_PATH = D('AUGMENTED_DATA_PATH', f'{DATA_PATH}/augmented')
AUGMENTED_LABELS_PATH = D('AUGMENTED_LABELS_PATH', f'{AUGMENTED_DATA_PATH}/labels')
AUGMENTED_IMAGES_PATH = D('AUGMENTED_IMAGES_PATH', f'{AUGMENTED_DATA_PATH}/images')

MAIN_CSV_PATH = D('MAIN_CSV_PATH', f'{DATA_PATH}/entities.csv')
SPLIT_DATA_PATH = D('SPLIT_DATA_PATH', f'{DATA_PATH}/split')
